#Kubernetes service manifest for your 
#web servers to expose them within the cluster
apiVersion: v1
kind: Service
metadata:
  name: basic-server
spec:
  selector:
    app: basic-server
  ports:
  - name: http
    port: 80
    targetPort: 3000
