apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-server
spec:
  replicas: 8
  selector:
    matchLabels:
      app: basic-server
  template:
    metadata:
      labels:
        app: basic-server
    spec:
      containers:
      - name: basic-server
        image: https://github.com/savchydev/chaos-experiment/blob/main/basic-server/Dockerfile
        ports:
        - containerPort: 3000
