apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: web-server-liveness-probe
  namespace: default
spec:
  # The target application container
  appinfo:
    appns: default
    applabel: app=web-server
    appkind: deployment
  # The probe that we want to execute
  chaosServiceAccount: litmus
  monitoring: false
  experiments:
    - name: liveness-probe
      spec:
        components:
          env:
            - name: APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_LABEL
              value: "app=web-server"
            - name: APP_KIND
              value: "deployment"
            - name: APP_CONTAINER
              value: "web-server"
            - name: LIVENESS_PROBE_PATH
              value: "/healthz"
            - name: LIVENESS_PROBE_PORT
              value: "8080"
            - name: FAILURE_TYPE
              value: "livenessProbe"
            - name: CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: CHAOS_ENGINE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          labels:
            name: liveness-probe
          annotations:
            prometheus.io/scrape: "false"
