version: '3'

services:
  telegraf:
    image: telegraf:1.17-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.8
    ports:
      - "8888:8888"
    depends_on:
      - influxdb

  kapacitor:
    image: kapacitor:1.5
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    depends_on:
      - influxdb
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - influxdb

volumes:
  influxdb:
