apiVersion: chaos-mesh.org/v1alpha1
kind: ChaosExperiment
metadata:
  name: delay-experiment
spec:
  action:
    netem:
      # Specify the deployment name and namespace
      selector:
        labelSelectors:
          'app.kubernetes.io/name': web-server
          'app.kubernetes.io/instance': web-deployment
      # Set the network delay to 100ms
      delay: 100ms
      # Set the packet loss to 10%
      loss: 10%
  scheduler:
    cron: '@every 5m'
  duration: '1h'
