apiVersion: chaos-mesh.org/v1alpha1
kind: ChaosExperiment
metadata:
  name: liveness-experiment
spec:
  action:
    podKill:
      # Specify the deployment name and namespace
      selector:
        labelSelectors:
          'app.kubernetes.io/name': web-server
          'app.kubernetes.io/instance': web-deployment
      # Set the number of pods to kill
      mode: one
  scheduler:
    cron: '@every 5m'
  duration: '1h'
