apiVersion: apps/v1
kind: Deployment
metadata:
  name: popeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popeye
  template:
    metadata:
      labels:
        app: popeye
    spec:
      containers:
        - name: popeye
          image: your-registry/popeye:latest
          command: ["popeye"]
          args: ["-c", "/config/config.yaml"]
          volumeMounts:
            - name: popeye-config
              mountPath: /config
      volumes:
        - name: popeye-config
          configMap:
            name: popeye-config
