apiVersion: v1
kind: Namespace
metadata:
  name: popeye

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: popeye
  namespace: popeye
  labels:
    app: popeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popeye
  template:
    metadata:
      labels:
        app: popeye
    spec:
      containers:
        - name: popeye
          image: derailed/popeye:v0.9.5
          args:
            - "-c"
            - "config.yaml"
          volumeMounts:
            - name: popeye-config
              mountPath: /etc/popeye
      volumes:
        - name: popeye-config
          configMap:
            name: popeye-config

---

apiVersion: v1
kind: Service
metadata:
  name: popeye
  namespace: popeye
spec:
  selector:
    app: popeye
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
