apiVersion: apps/v1
kind: Deployment
metadata:
  name: popeye
  labels:
    app: popeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popeye
  template:
    metadata:
      labels:
        app: popeye
    spec:
      containers:
      - name: popeye
        image: derailed/popeye:latest
        imagePullPolicy: Always
        command:
        - popeye
        - -c
        - /dev/null
