apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.33.1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
          items:
          - key: prometheus.yml
            path: prometheus.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'basic-server'
        static_configs:
          - targets: ['basic-server:80']

        
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: basic-server-monitor
  labels:
    app: basic-server
spec:
  selector:
    matchLabels:
      app: basic-server
  endpoints:
  - port: web

