global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'web-server'
    static_configs:
      - targets: ['web-server:3000']
    
  - job_name: 'chaos-exporter'
    static_configs:
      - targets: ['chaos-exporter:8080']
