apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}



  # In this example, the replicas value is parameterized using 
  # {{ .Values.replicas }}, which is defined in the values.yaml file. 
  # The resources.cpu and resources.memory values are also parameterized using 
  # {{ .Values.resources.cpu }} and {{ .Values.resources.memory }}, 
  # respectively, which are also defined in the values.yaml file.