apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          periodSeconds: {{ .Values.periodSeconds }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          periodSeconds: {{ .Values.periodSeconds }}



  # In this example, the replicas value is parameterized using 
  # {{ .Values.replicas }}, which is defined in the values.yaml file. 
  # The resources.cpu and resources.memory values are also parameterized using 
  # {{ .Values.resources.cpu }} and {{ .Values.resources.memory }}, 
  # respectively, which are also defined in the values.yaml file.
